#!/usr/bin/env bash
# Smoke test for ALL 8 bi-encoder recipes.
#
# Builds a tiny synthetic dataset, runs the mining + scoring side-stages
# needed by Recipes 2/3/6/7, trains a model for each recipe (1 epoch,
# batch 4), and verifies the saved artifact behaves as the recipe promises.
#
# Run from the repo root:
#   bash scripts/embedding_bi_encoder/smoke_test_all.sh           # all 8
#   bash scripts/embedding_bi_encoder/smoke_test_all.sh 3         # just Recipe 3
#   bash scripts/embedding_bi_encoder/smoke_test_all.sh 2 3 6 7   # subset
#
# Heads up — first run downloads ~150 MB of HF models for mining + scoring
# (a small retriever + a tiny cross-encoder). After that the smoke is
# ~1-2 min per recipe on CPU.

set -euo pipefail

# ── Paths ───────────────────────────────────────────────────────────────────
PAIR_DIR="data/processed/smoke-bi-encoder"
MINED_DENSE_DIR="data/processed/smoke-mined-dense"
MINED_ENSEMBLE_DIR="data/processed/smoke-mined-ensemble"
DISTILL_DIR="data/processed/smoke-distill"
SILVER_DIR="data/processed/smoke-silver"

CONFIG_DIR="configs/embedding/bi_encoder"
OUT_BASE="outputs"

# ── Models used by the mining + scoring side-stages ─────────────────────────
# Both small, different from the student (all-MiniLM-L6-v2). The recipe's
# rule "don't mine with the student" is met by using paraphrase-MiniLM-L3.
SMOKE_RETRIEVER="sentence-transformers/paraphrase-MiniLM-L3-v2"
SMOKE_CROSS_ENCODER="cross-encoder/ms-marco-MiniLM-L-6-v2"

# ── Helpers ─────────────────────────────────────────────────────────────────
banner() {
    echo
    echo "============================================================"
    echo "$1"
    echo "============================================================"
}

prepare_pair_dataset() {
    if [[ -d "$PAIR_DIR" ]]; then
        echo "[skip] $PAIR_DIR exists — reusing."
        return
    fi
    banner "Prep │ build synthetic (anchor, positive) pairs"
    python examples/embedding_bi_encoder/prepare_smoke.py \
        --out-dir "$PAIR_DIR" \
        --n-train 100 --n-val 24 --n-test 24
}

mine_dense() {
    if [[ -d "$MINED_DENSE_DIR" ]]; then
        echo "[skip] $MINED_DENSE_DIR exists — reusing."
        return
    fi
    banner "Prep │ mine hard negatives (dense)"
    python scripts/embedding_bi_encoder/mine_hard_negatives.py \
        --input-dataset "$PAIR_DIR" \
        --output-dir    "$MINED_DENSE_DIR" \
        --strategy dense \
        --retriever     "$SMOKE_RETRIEVER" \
        --cross-encoder "$SMOKE_CROSS_ENCODER" \
        --num-negatives 3 \
        --relative-margin 0.4 \
        --range-min 2 --range-max 30 \
        --batch-size 16
}

mine_ensemble() {
    if [[ -d "$MINED_ENSEMBLE_DIR" ]]; then
        echo "[skip] $MINED_ENSEMBLE_DIR exists — reusing."
        return
    fi
    banner "Prep │ mine hard negatives (ensemble = dense + BM25)"
    python scripts/embedding_bi_encoder/mine_hard_negatives.py \
        --input-dataset "$PAIR_DIR" \
        --output-dir    "$MINED_ENSEMBLE_DIR" \
        --strategy ensemble \
        --retriever     "$SMOKE_RETRIEVER" \
        --bm25 \
        --cross-encoder "$SMOKE_CROSS_ENCODER" \
        --num-negatives 3 \
        --relative-margin 0.4 \
        --range-min 2 --range-max 30 \
        --batch-size 16
}

score_distill() {
    if [[ -d "$DISTILL_DIR" ]]; then
        echo "[skip] $DISTILL_DIR exists — reusing."
        return
    fi
    banner "Prep │ score dense-mined with cross-encoder (→ distill)"
    python scripts/embedding_bi_encoder/score_with_cross_encoder.py \
        --input-dataset "$MINED_DENSE_DIR" \
        --output-dir    "$DISTILL_DIR" \
        --cross-encoder "$SMOKE_CROSS_ENCODER" \
        --batch-size 16
}

score_silver() {
    if [[ -d "$SILVER_DIR" ]]; then
        echo "[skip] $SILVER_DIR exists — reusing."
        return
    fi
    # Recipe 7's framing: silver labels = teacher scores over an UNLABELLED
    # pool, generated by a (typically custom) cross-encoder. For the smoke
    # we reuse the same off-the-shelf CE — the plumbing is identical.
    banner "Prep │ score ensemble-mined with cross-encoder (→ silver distill)"
    python scripts/embedding_bi_encoder/score_with_cross_encoder.py \
        --input-dataset "$MINED_ENSEMBLE_DIR" \
        --output-dir    "$SILVER_DIR" \
        --cross-encoder "$SMOKE_CROSS_ENCODER" \
        --batch-size 16
}

train_and_verify() {
    local n="$1"
    local config="${CONFIG_DIR}/smoke_r${n}.yaml"
    local out_final="${OUT_BASE}/smoke_bi_encoder_r${n}/final"
    local processed_dir
    processed_dir=$(python -c "import yaml,sys; print(yaml.safe_load(open('${config}'))['processed_dir'])")

    banner "Recipe ${n} │ train"
    python scripts/embedding_bi_encoder/train_bi_encoder.py --config "$config"

    banner "Recipe ${n} │ verify"
    python examples/embedding_bi_encoder/verify_smoke.py \
        --recipe "$n" \
        --model-dir "$out_final" \
        --processed-dir "$processed_dir"
}

# Each recipe declares what prep stages it needs so subset runs work.
run_recipe() {
    local n="$1"
    case "$n" in
        1|4|8)
            prepare_pair_dataset
            ;;
        2)
            prepare_pair_dataset; mine_dense
            ;;
        3)
            prepare_pair_dataset; mine_dense; score_distill
            ;;
        5)
            # Recipe 5 is a TWO-STAGE training: stage 1 = Recipe 4
            # (1D Matryoshka + GradCache, big batch — teaches the dim
            # axis), stage 2 = Recipe 5 (2D, small batch, continued from
            # stage 1 — adds the depth axis). AdaptiveLayer is structurally
            # incompatible with cached losses, so this split is the only
            # way to keep GradCache's big-batch quality benefit.
            prepare_pair_dataset
            if [[ ! -d "${OUT_BASE}/smoke_bi_encoder_r4/final" ]]; then
                banner "Recipe 5 │ stage 1 prerequisite (= Recipe 4)"
                train_and_verify 4
            else
                echo "[skip] stage 1 (Recipe 4 output) exists — reusing."
            fi
            ;;
        6)
            prepare_pair_dataset; mine_ensemble
            ;;
        7)
            prepare_pair_dataset; mine_ensemble; score_silver
            ;;
        *)
            echo "Unknown recipe number: $n (expected 1-8)" >&2
            exit 2
            ;;
    esac
    train_and_verify "$n"
}

# ── Main ───────────────────────────────────────────────────────────────────
if [[ $# -eq 0 ]]; then
    RECIPES=(1 2 3 4 5 6 7 8)
else
    RECIPES=("$@")
fi

PASSED=()
FAILED=()
for n in "${RECIPES[@]}"; do
    # Subshell ensures `set -e` aborts on the first failure inside the
    # recipe stage, while the outer `if` catches the failure so the loop
    # can keep going through later recipes.
    if (run_recipe "$n"); then
        PASSED+=("$n")
    else
        FAILED+=("$n")
        echo
        echo ">>> Recipe ${n} FAILED — continuing with remaining recipes."
    fi
done

banner "Summary"
echo "Passed: ${PASSED[*]:-(none)}"
echo "Failed: ${FAILED[*]:-(none)}"

if [[ ${#FAILED[@]} -gt 0 ]]; then
    exit 1
fi
echo "ALL SMOKE TESTS PASSED."